spring:
  application:
    name: toolflow
  sql:
    init:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://185.194.216.41:5432/toolflow
    # url: jdbc:postgresql://localhost:5432/toolflow
    username: postgres
    password: "secret"
    hikari:
      maxLifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    baseline-on-migrate: true
    table: flyway_${spring.application.name}
    enabled: true
    outOfOrder: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc.lob.non_contextual_creation: true
        generate_statistics: false
    open-in-view: false

server:
  port: 9009

security:
  jwt:
    expiration-in-minutes: 30
    secret-key: bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
